name: Build

on:
  pull_request:
    branches: [ release, develop ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: true

      - name: Build
        run: docker run -v ${{ github.workspace }}:${{ github.workspace }} tgstation/byond:514.1565 DreamMaker "${{ github.workspace }}/naruto-evolution.dme"