name: Build

on:
  push:
    branches: [ master, develop, master-v1, develop-v1 ]
  pull_request:
    branches: [ master, develop, master-v1, develop-v1 ]
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      container: tgstation/byond:latest
      steps:
        - uses: actions/checkout@v2
        - name: Build
          run: |
            DreamMaker "$GITHUB_WORKSPACE/project-evolution.dme"