name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BYOND_VERSION: "514.1589"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          lfs: true

      - name: Build application
        run: docker run -v ${{ github.workspace }}:${{ github.workspace }} registry.douglasparker.dev/byond/byond:$BYOND_VERSION DreamMaker "${{ github.workspace }}/naruto-evolution.dme"