name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Beta Testing Server
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo "Installing 32 bit dependencies"
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

          echo "Installing unzip..."
          sudo apt-get install unzip

      - name: Install BYOND
        run: |
          curl -OL http://www.byond.com/download/build/513/513.1542_byond_linux.zip
          unzip *_byond_linux.zip
          cd byond
          sudo make install
          
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Build project
        run: |
          DreamMaker "$GITHUB_WORKSPACE/naruto-evolution.dme"
      
      - name: Deploy project
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "$SSH_KEY" > ~/.ssh/naruto-evolution

          cat > ~/.ssh/config <<EOF
          Host naruto-evolution
          HostName $SSH_HOST
          User $SSH_USER
          Port 22
          IdentityFile ~/.ssh/naruto-evolution
          EOF

          rsync --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.dme" naruto-evolution:~/naruto-evolution/beta/
          rsync --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.rsc" naruto-evolution:~/naruto-evolution/beta/

          ssh naruto-evolution -o StrictHostKeyChecking=no <<EOF
            mv --force ~/naruto-evolution/beta/naruto-evolution.dme ~/naruto-evolution/beta/beta.dme
            mv --force ~/naruto-evolution/beta/naruto-evolution.rsc ~/naruto-evolution/beta/beta.rsc
            systemctl restart naruto-evolution-beta
          EOF