name: Deploy

on:
  push:
    branches: [ master-v1 ]
  pull_request:
    branches: [ master-v1 ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Build project
        run: |
          DreamMaker "$GITHUB_WORKSPACE/naruto-evolution.dme"
      
      - name: Deploy project
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh "$SSH_USER"@"$SSH_HOST" -o StrictHostKeyChecking=no <<EOF
          EOF