name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      server:
        description: Server (official, beta, alpha)
        required: true
        default: official

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: true

      - name: Build
        run: docker run -v ${{ github.workspace }}:${{ github.workspace }} tgstation/byond:514.1565 DreamMaker "${{ github.workspace }}/naruto-evolution.dme"
        
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}
  
  Deploy:
    runs-on: ubuntu-20.04
    needs: [Build]
    steps:
      - name: Restore build
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}

      - name: Deploy project
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/naruto-evolution
          chmod 600 ~/.ssh/naruto-evolution

          cat > ~/.ssh/config <<EOF
          Host naruto-evolution
          HostName $SSH_HOST
          User $SSH_USER
          Port 22
          IdentityFile ~/.ssh/naruto-evolution
          EOF

          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.dmb" naruto-evolution:~/naruto-evolution/${{ github.event.inputs.server }}/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.rsc" naruto-evolution:~/naruto-evolution/${{ github.event.inputs.server }}/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/VERSION" naruto-evolution:~/naruto-evolution/${{ github.event.inputs.server }}/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/CHANGELOG.md" naruto-evolution:~/naruto-evolution/${{ github.event.inputs.server }}/

          ssh naruto-evolution -o StrictHostKeyChecking=no <<EOF
            mv --force ~/naruto-evolution/${{ github.event.inputs.server }}/naruto-evolution.dmb ~/naruto-evolution/${{ github.event.inputs.server }}/${{ github.event.inputs.server }}.dmb
            mv --force ~/naruto-evolution/${{ github.event.inputs.server }}/naruto-evolution.rsc ~/naruto-evolution/${{ github.event.inputs.server }}/${{ github.event.inputs.server }}.rsc
            if [[ ${{ github.event.inputs.server }} == "beta" ]] || [[ ${{ github.event.inputs.server }} == "alpha" ]]
              systemctl restart naruto-evolution-${{ github.event.inputs.server }}
            else
              systemctl restart naruto-evolution
            fi
          EOF