name: Release

on:
  release:
    types: [published]

env:
  BYOND_VERSION: "514.1589"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          lfs: true

      - name: Build application
        run: |
          docker run -v ${{ github.workspace }}:${{ github.workspace }} ghcr.io/douglasparker/byond:$BYOND_VERSION DreamMaker "${{ github.workspace }}/naruto-evolution.dme"
          echo "${{ github.event.release.tag_name }}" > "${{ github.workspace }}/VERSION"

          if [ ${{ github.event.release.prerelease }} == 'true' ]; then
            echo "PRERELEASE" > "${{ github.workspace }}/PRERELEASE"
          fi

      - name: Deploy to server
        if: github.event.release.prerelease == false
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "pkill DreamDaemon"
            sshpass -p "${{ secrets.SSH_PASSWORD }}" scp "${{ github.workspace }}/naruto-evolution.dmb" ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/opt/naruto-evolution/