name: Release (Beta Server)

on:
  push:
    branches: [ release ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      BYOND_VERSION: "514.1576"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: true

      - name: Build
        run: docker run -v ${{ github.workspace }}:${{ github.workspace }} douglasparker/byond:$BYOND_VERSION DreamMaker "${{ github.workspace }}/naruto-evolution.dme"

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}

  Deploy:
    runs-on: ubuntu-20.04
    needs: [Build]
    env:
      BYOND_VERSION: "514.1576"
    steps:
      - name: Restore build
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}

      - name: Deploy project
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/naruto-evolution
          chmod 600 ~/.ssh/naruto-evolution

          cat > ~/.ssh/config <<EOF
          Host naruto-evolution
          HostName $SSH_HOST
          User $SSH_USER
          Port 22
          IdentityFile ~/.ssh/naruto-evolution
          EOF

          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.dmb" naruto-evolution:/opt/naruto-evolution/beta/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.rsc" naruto-evolution:/opt/naruto-evolution/beta/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/VERSION" naruto-evolution:/opt/naruto-evolution/beta/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/CHANGELOG.md" naruto-evolution:/opt/naruto-evolution/beta/

          ssh naruto-evolution -o StrictHostKeyChecking=no <<EOF
            mv --force /opt/naruto-evolution/beta/naruto-evolution.dmb /opt/naruto-evolution/beta/beta.dmb
            mv --force /opt/naruto-evolution/beta/naruto-evolution.rsc /opt/naruto-evolution/beta/beta.rsc
            echo "-beta" >> /opt/naruto-evolution/beta/VERSION

            docker stop naruto-evolution-beta
            docker container rm naruto-evolution-beta
            docker run --name naruto-evolution-beta --volume /opt/naruto-evolution/beta:/opt/naruto-evolution/beta --publish 1338:1338 --restart unless-stopped --detach douglasparker/byond:$BYOND_VERSION DreamDaemon /opt/naruto-evolution/beta/beta.dmb -ports 1338 -invisible
          EOF