name: Release

on:
  release:
    types: [published]

env:
  BYOND_VERSION: "514.1584"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          lfs: true
      
      - name: Build application
        run: |
          docker run -v ${{ github.workspace }}:${{ github.workspace }} douglasparker/byond:$BYOND_VERSION DreamMaker "${{ github.workspace }}/naruto-evolution.dme"
          echo "${{ github.event.release.tag_name }}" > "${{ github.workspace }}/VERSION"

          if [ ${{ github.event.release.action == 'prereleased' }} ]; then
            echo "PRERELEASE" > "${{ github.workspace }}/PRERELEASE"
          fi

      - name: Login to the Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract repository metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      
      - name: Build the Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Install Changelog Parser
        run: |
          sudo git clone https://github.com/douglasparker/changelog-parser.git /changelog-parser
          sudo chmod +x /changelog-parser/changelog-parser.py
      
      - name: Create a public pre-release without the changelog
        if: github.event.release.action == 'prereleased'
        run: |
          gh auth login --with-token <<< ${{ secrets.ACTIONS }}
          gh release create ${{ github.event.release.tag_name }} --title ${{ github.event.release.tag_name }} --prerelease --notes "## [${{ github.event.release.tag_name }}] $(date +"%Y-%m-%d")
            *Release notes are not provided for pre-releases.*" --repo douglasparker/naruto-evolution-community
      
      - name: Create a public release with the changelog
        if: github.event.release.action == 'released'
        run: |
          gh auth login --with-token <<< ${{ secrets.ACTIONS }}
          gh release create ${{ github.event.release.tag_name }} --title ${{ github.event.release.tag_name }} --notes "${{ github.event.release.body }}" --repo douglasparker/naruto-evolution-community
      
      - name: Deploy the Docker image to the server
        if: github.event.release.action == 'released'
        run: |
          cat > ~/.ssh/config <<EOF
          Host naruto-evolution
          HostName $SSH_HOST
          User $SSH_USER
          Port 22
          EOF

          ssh naruto-evolution -o StrictHostKeyChecking=no <<EOF
            docker stop naruto-evolution
            docker rm naruto-evolution
            docker pull ghcr.io/douglasparker/naruto-evolution:latest
            docker run --detach \
              --name naruto-evolution \
              --volume /opt/naruto-evolution/cfg:/opt/naruto-evolution/cfg \
              --volume /opt/naruto-evolution/saves:/opt/naruto-evolution/saves \
              --volume /opt/naruto-evolution/logs:/opt/naruto-evolution/logs \
              --publish 1337:1337 \
              --restart unless-stopped \
              ghcr.io/douglasparker/naruto-evolution:latest DreamDaemon /opt/naruto-evolution/naruto-evolution.dmb -ports 1337
          EOF