name: Release (Official Server)

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: true

      - name: Build
        run: docker run -v ${{ github.workspace }}:${{ github.workspace }} tgstation/byond:latest DreamMaker "${{ github.workspace }}/naruto-evolution.dme"

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}

  Release:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}
      
      - name: Package
        run: |
          sudo apt-get install zip
          sudo mkdir -p /naruto-evolution
          sudo cp -p ${{ github.workspace }}/naruto-evolution.dmb /naruto-evolution/naruto-evolution.dmb
          sudo cp -p ${{ github.workspace }}/naruto-evolution.rsc /naruto-evolution/naruto-evolution.rsc
          sudo cp -p ${{ github.workspace }}/VERSION /naruto-evolution/VERSION
          sudo cp -p ${{ github.workspace }}/CHANGELOG.md /naruto-evolution/CHANGELOG.md
          sudo zip -r ${{ github.workspace }}/naruto-evolution-$(cat ${{ github.workspace }}/VERSION).zip /naruto-evolution
          sudo tar -czf ${{ github.workspace }}/naruto-evolution-$(cat ${{ github.workspace }}/VERSION).tar.gz /naruto-evolution
      
      - name: Release
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh release create $(cat ${{ github.workspace }}/VERSION) --title $(cat ${{ github.workspace }}/VERSION) --notes-file ${{ github.workspace }}/CHANGELOG.md --target ${{ github.sha }}
          gh release upload $(cat ${{ github.workspace }}/VERSION) ${{ github.workspace }}/naruto-evolution-$(cat ${{ github.workspace }}/VERSION).zip
          gh release upload $(cat ${{ github.workspace }}/VERSION) ${{ github.workspace }}/naruto-evolution-$(cat ${{ github.workspace }}/VERSION).tar.gz
          gh release create $(cat ${{ github.workspace }}/VERSION) --title $(cat ${{ github.workspace }}/VERSION) --notes-file ${{ github.workspace }}/CHANGELOG.md --repo lavenblade/naruto-evolution-public
  
  Deploy:
    runs-on: ubuntu-latest
    needs: [Release]
    steps:
      - name: Restore build
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/*
          key: ${{ github.sha }}

      - name: Deploy project
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/naruto-evolution
          chmod 600 ~/.ssh/naruto-evolution

          cat > ~/.ssh/config <<EOF
          Host naruto-evolution
          HostName $SSH_HOST
          User $SSH_USER
          Port 22
          IdentityFile ~/.ssh/naruto-evolution
          EOF

          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.dmb" naruto-evolution:~/naruto-evolution/official/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/naruto-evolution.rsc" naruto-evolution:~/naruto-evolution/official/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/VERSION" naruto-evolution:~/naruto-evolution/official/
          rsync -e "ssh -o StrictHostKeyChecking=no" --archive --verbose --progress --human-readable "$GITHUB_WORKSPACE/CHANGELOG.md" naruto-evolution:~/naruto-evolution/official/
          
          ssh naruto-evolution -o StrictHostKeyChecking=no <<EOF
            mv --force ~/naruto-evolution/official/naruto-evolution.dmb ~/naruto-evolution/official/official.dmb
            mv --force ~/naruto-evolution/official/naruto-evolution.rsc ~/naruto-evolution/official/official.rsc
            systemctl restart naruto-evolution
          EOF